[package]
name = "dos101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
crseo = "0.4.1"
dos-actors = { path = "../dos-actors", features = ["ceo", "apache-arrow"] }
tokio = "1.18.2"
